Propina Carrasco/Proyecto Propina/Proyecto Propina/PropinaWeb/Controllers/CuentaController.cs
using BL;
using ET;
using PropinaWeb.ViewModel.CuentaViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PropinaWeb.Controllers
{
    public class CuentaController : Controller
    {
        public ActionResult Login()
        {
            if (Session["TipoUsuario"] == null)
            {
                try
                {
                    return View(new LoginViewModel());
                }
                catch (ProyectoException ex)
                {
                    ViewBag.Mensaje = ex.Message;
                    return View("~/Views/Shared/_Mensajes.cshtml");
                }
            }
            else
            {
                try
                {
                    return RedirectToAction("Index", "Home");
                }
                catch (ProyectoException ex)
                {
                    ViewBag.Mensaje = ex.Message;
                    return View("~/Views/Shared/_Mensajes.cshtml");
                }
            }
        }


        //POST: Account/Login
        [HttpPost]
        public ActionResult Login(LoginViewModel loginVM)
        {
            try
            {
                UsuarioBL usuarioBL = new UsuarioBL();
                Usuario usu = usuarioBL.ingresarUsuario(loginVM.NombreUsuario, loginVM.Password);
                if (usu != null)
                {
                    Session["IdUsuario"] = usu.Id;
                    Session["NombreUsuario"] = usu.NombreUsuario;
                    Session["TipoUsuario"] = usu.Tipo;

                    return RedirectToAction("Index", "Home");
                }

                loginVM.Mensaje = "Datos erróneos. Por favor, inténtelo otra vez.";
                return View(loginVM);
            }
            catch (ProyectoException ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
        }

        //GET: Account/LogOff
        public ActionResult LogOff()
        {
            try
            {
                Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            catch (ProyectoException ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View("~/Views/Shared/_Mensajes.cshtml");
            }
        }
    }
}

Propina Carrasco/Proyecto Propina/Proyecto Propina/PropinaWeb/Views/Cuenta/Login.cshtml
@model PropinaWeb.ViewModel.CuentaViewModel.LoginViewModel

@{
    ViewBag.Title = "Login";
}

<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <h2>Iniciar Sesión</h2>
        @using (Html.BeginForm("Login", "Cuenta", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.NombreUsuario, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.NombreUsuario, new { @id = "nombreUsuario", @class = "form-control", @placeholder = "Nombre Usuario" })
                @Html.ValidationMessageFor(model => model.NombreUsuario, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Password, new { @id = "pass", @class = "form-control", @placeholder = "Contraseña", type = "password" })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                <label class="text-danger">@Model.Mensaje</label>
            </div>

            <button type="submit" class="btn btn-primary">Ingresar</button>
        }
    </div>
    <div class="col-sm-4"></div>
</div>